### ISSUE TITLE
STM32F103C8t6 Connection (SPI)

### ISSUE THREAD

**Issue by mhyoosefian** [Seeed-Studio/Seeed_ADIS16470#1]
Hi,

Thanks for the contribution. Can I get raw data from my ADIS using SPI interface? More precisely, I want to connect my ADIS directly to STM32F103 and get data using SPI protocol. Can I use this library? If not, do you know any other source code to do so?

Thanks in advance.

**Comment by hareendranmg** [comment]
Hi @mhyoosefian ,

Did you find any solution?

**Comment by mhyoosefian** [comment]
> Hi @mhyoosefian ,
> 
> Did you find any solution?

Hi @hareendranmg, yeah. As far as I remember, ultimately I found a source code on the web that with slight modifications could do that.

**Comment by hareendranmg** [comment]
Hi @mhyoosefian , is there any way that you can share with me?

**Comment by mhyoosefian** [comment]
> Hi @mhyoosefian , is there any way that you can share with me?

Hey,
yes, shoot me your email in my LinkedIn (can be found in my profile).
